# Generated by Django 4.2 on 2023-05-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binaryapp', '0003_binarytreenode_level_binarytreenode_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binarytreenode',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
